version: '3.8'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - app_network


networks:
  app_network:
    name: app_network