apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  namespace: python-app
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: fastapi_app:latest
        ports:
        - containerPort: 8088
        imagePullPolicy: Never
